# Generated by Django 2.0.7 on 2019-09-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectores', '0003_preferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencia',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lectores.Lector'),
        ),
    ]
