# Generated by Django 2.0.7 on 2019-10-05 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='Fecha Mod')),
                ('img', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('body_1', models.TextField(verbose_name='Texto Superior')),
                ('body_2', models.TextField(verbose_name='Texto Superior Inf')),
                ('body_3', models.TextField(verbose_name='Texto Superior Cen')),
                ('body_4', models.TextField(verbose_name='Texto Baja')),
            ],
            options={
                'verbose_name': 'Cuerpo',
                'verbose_name_plural': 'Cuerpo',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
