# Generated by Django 2.0.7 on 2019-10-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocialNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Redes Sociales',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Model Footer', 'verbose_name_plural': 'Model Footer'},
        ),
        migrations.AddField(
            model_name='footersocialnet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Footer', verbose_name='Footer'),
        ),
    ]
