# Generated by Django 2.0.7 on 2019-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191012_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='surname',
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default='', max_length=20, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
